//src/pages/survival/api/dummyCharacters.tsx
export const dummyCharacters = [
  {
    characterId: 1,
    level: 1,
    title: '오늘밤 두잇두잇',
    nickname: '익찌리릿',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: true,
  },
  {
    characterId: 1,
    level: 1,
    title: '짜릿짜릿한',
    nickname: '김익환',
    nicknameColor: 'red',
    isAlive: false,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '솔비 피쳐링',
    nickname: '김익방',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '엠카 엔딩요정',
    nickname: '찌리릿익',
    nicknameColor: 'red',
    isAlive: false,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '저슦두잇두잇',
    nickname: '나익키',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '오늘밤 두잇두잇',
    nickname: '익찌리릿',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '오늘밤 두잇두잇',
    nickname: '익찌리릿',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '짜릿짜릿한',
    nickname: '김익환',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '솔비 피쳐링',
    nickname: '김익방',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '엠카 엔딩요정',
    nickname: '찌리릿익',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '저슦두잇두잇',
    nickname: '나익키',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '오늘밤 두잇두잇',
    nickname: '익찌리릿',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '짜릿짜릿한',
    nickname: '김익환',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '솔비 피쳐링',
    nickname: '김익방',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '엠카 엔딩요정',
    nickname: '찌리릿익',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '저슦두잇두잇',
    nickname: '나익키',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '오늘밤 두잇두잇',
    nickname: '익찌리릿',
    nicknameColor: 'red',
    isAlive: false,
    isRevive: false,
  },
  {
    characterId: 1,
    level: 1,
    title: '솔비 피쳐링',
    nickname: '김익방',
    nicknameColor: 'red',
    isAlive: true,
    isRevive: true,
  },
];
