version: '3'

services:
  quizdotbe:
    build:
      context: ./quizdot-server
      dockerfile: Dockerfile
    image: feelgod/quizdotbe:latest
    container_name: quizdotbe
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=server
    networks:
      - app-network

  quizdotfe:
    build:
      context: ./quizdot-client
      dockerfile: Dockerfile
    image: feelgod/quizdotfe:latest
    container_name: quizdotfe
    ports:
      - "8082:5173"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    restart : always
    ports:
      - "9090:8080"
    user: root
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart : always
    networks:
      - app-network
  
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    external: true

